### ISSUE TITLE
Calibration Result

### ISSUE THREAD

**Issue by ShihanWang** [MegviiRobot/CamOdomCalibraTool#1]
**Issue summary**
使用一个标定好的相机和误差为2%的Odomtry测试标定：
1、虽然有标定结果，但是和实际相差挺大，原因尚且不知；
2、标定结果显示z值为0，所以这个标定其实是只标x/y/yawl吗？还是我的数据问题？
3、是否有官方标定数据集？或者能不能把具体的标定流程和需要注意的事项放在github上？

**Comment by npcdna** [comment]
+1

**Comment by kongdaqing** [comment]
+1

**Comment by Jafzdf** [comment]
代码要注意一下几个问题：
1、由于不同AGV小车的相机安装不同，所以，camera和odom各自的坐标系和我们定义的坐标系可能会不一样。代码里面是先标定相机坐标系相对odom坐标系旋转中的pitch和roll角，然后把相机坐标系矫正到有一个轴垂直地面，把相机的观测转换成二维平面上。因此这里需要注意，相机的哪两个轴被定义为二维平面上的x和y，去与odom的二维观测对齐，这个在代码中是需要自己留意修改的。
2、z值为0，是因为只有相机和odom的观测，外参平移的z值是不可观的，是标定不出来的。
3、还需要注意的是：
    我们的AGV小车的odom输出数据是线速度和角速度，所以我们又将他们通过工业内参，转换成了左右轮速；
    标定中，尽力避免左右轮打滑的情况，保持速度平稳，又丰富旋转和平移运动。

**Comment by npcdna** [comment]
您好，能问下你们小车相机和轮式里程计有经过同步处理吗，还是直接连上ｒｏｓ发出来，没管同步处理

**Comment by Jafzdf** [comment]
代码里面会有时间同步。



---Original---

**Comment by npcdna** [comment]
您好，我们目前的小车是相机朝小车移动的正前放置，我看代码里应该和你们代码里默认一样吧，不过之后打算改成相机45度朝上放置，不知道能否标定

**Comment by Jafzdf** [comment]
大家可以结合这篇博客"[关于camera和odometer标定](https://blog.csdn.net/wq1psa78/article/details/103512283)"来做标定.

**Comment by chaizheng2157** [comment]
> **Issue summary**
> 使用一个标定好的相机和误差为2%的Odomtry测试标定：
> 1、虽然有标定结果，但是和实际相差挺大，原因尚且不知；
> 2、标定结果显示z值为0，所以这个标定其实是只标x/y/yawl吗？还是我的数据问题？
> 3、是否有官方标定数据集？或者能不能把具体的标定流程和需要注意的事项放在github上？

平移外参z轴在平面运动下不可观。
标定注意事项可参考中[标定系列二 | 实践之Camera-Odometry标定](https://zhuanlan.zhihu.com/p/101727151)的第3部分。

**Comment by chaizheng2157** [comment]
> 您好，能问下你们小车相机和轮式里程计有经过同步处理吗，还是直接连上ｒｏｓ发出来，没管同步处理

建议先对传感器进行时间同步（软同步也可以）。目前程序里只是做了数据筛选来减小不同步的影响。

**Comment by chaizheng2157** [comment]
> 您好，我们目前的小车是相机朝小车移动的正前放置，我看代码里应该和你们代码里默认一样吧，不过之后打算改成相机45度朝上放置，不知道能否标定

可以标定的。

**Comment by arenas7307979** [comment]
hii，您好
当我改变wheelodomaCallback中的轮胎的工业内参（rl = rr = 0.035, baseline = 0.2)
则得到以下结果

![image](https://user-images.githubusercontent.com/5019568/78498510-38748880-777d-11ea-9cb1-5d3c419ed06f.png)

不过当替换rr = rl = 0.1（默认） baseline = 0.5 时，则校正看似正常

可以请作者提供bag file，想针对姿势的姿态对应做一个参考
thanks

**Comment by Jafzdf** [comment]
我已经不在公司了，也没有bag包了，出现图片那种情况，可能是你标定数据集有比较多的直线运动。要注意尽可能多的旋转加平移

---Original---

**Comment by arenas7307979** [comment]
Ok, I'll try. Thank you very much for your reply

**Comment by arenas7307979** [comment]
@Jafzdf 

j大您好，以下个问题想请教您
您博客的说明如下

想询问这个注解（左边为原始的感测器原始座标，右手边为当下转换对应）
odom前进应该是x轴，相对于cam应对应z轴(sync_tmp.scan_match_results[0] = camDatas[i].tlc[2])
但代码中却是odom x轴对应cam x轴，是因为来自旋转轴y轴转向的原因吗

![image](https://user-images.githubusercontent.com/5019568/78534254-b0de5680-781c-11ea-988b-c6f779f4fdf2.png)

**Comment by Jafzdf** [comment]
你说的很对，你截图那里的操作就是让旋转轴垂直地面向上，也就是你说的为符号，所以你看到我那里，当axis（1）为正时，我乘了负号



---Original---

**Comment by arenas7307979** [comment]
@Jafzdf 
感谢您回覆

最后请教一个问题, 在代码的最后我尝试用不同的方式转换四元数与euler之间
参考了这份资料
https://www.cntofu.com/book/46/osvr/quat_euler_hu_zhuan.md
不过与作者的res[2]与res[1]正好相反,
此外也尝试了
使用Eigen本身的转换去得到euler角度
![image](https://user-images.githubusercontent.com/5019568/78850519-0481b780-7a4a-11ea-8a0d-634ce8ac2843.png)
不过答案好像也不相同

**Comment by Jafzdf** [comment]
让四元数转换为欧拉角，只是为了我们方便理解，知道在哪个轴转了多少度，比较形象。有很多种转换方式，这个没必要纠结，你用你的方式转换成欧拉角，在用你的方式转换回四元数，都是可以的。最终我们拿来用的都是这个旋转四元数，而不是欧拉角，四元数是一致。



---Original---

**Comment by arenas7307979** [comment]
好的, 受益非浅
感谢您们的开源以及提点
