### ISSUE TITLE
代码解读

### ISSUE THREAD

**Issue by BIT-wangzb** [MegviiRobot/CamOdomCalibraTool#2]
将约束条件xy = -zw，转换为ax^2+bx+c=0是怎样转换的？

**Comment by chaizheng2157** [comment]
> 将约束条件xy = -zw，转换为ax^2+bx+c=0是怎样转换的？

可参考[标定系列二 | 实践之Camera-Odometry标定](https://zhuanlan.zhihu.com/p/101727151)中的3.2.1
