### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by JadTawil-theonly** [MegviiRobot/CamOdomCalibraTool#4]
Hello, I have a few questions about the implementation.

In SolveConstraintqyx, can you provide the mathematical details of this function? I understand that the constraints are being used as per the referenced paper. I cannot see how the transformations to the form ax^2+ bx + c = 0 is being done

Thanks

**Comment by lucasZhang-Satori** [comment]
I have the same question ,can u explain this? Thanks
