### ISSUE TITLE
correctCamera function

### ISSUE THREAD

**Issue by JadTawil-theonly** [MegviiRobot/CamOdomCalibraTool#7]
Why is it necessary to "correct" the camera translation with the the Ryx matrix?

**Comment by chaizheng2157** [comment]
> Why is it necessary to "correct" the camera translation with the the Ryx matrix?

We want to make it be a pure 2d calibration problem, so we convert the camera translation from camera coordinate to plane coordinate by the Ryx matrix.

**Comment by JadTawil-theonly** [comment]
Perfect, thank you!
